import { existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { loadFounderContext } from "./founder-context.js";

export interface DailyInboxConfig {
  enabled?: boolean;
  vaultJunoRoot?: string;
  inboxSubdir?: string;
  filenamePattern?: string;
  profileFile?: string;
  deletePreviousDay?: boolean;
}

export interface DailyInboxResult {
  status: "created" | "skipped" | "disabled" | "error";
  filePath?: string;
  deleted?: string[];
  reason?: string;
}

function readCfgYaml(workbench: string): { vaultPath: string; vaultJunoRoot: string } | null {
  const p = path.join(workbench, "config.yaml");
  if (!existsSync(p)) return null;
  const raw = readFileSync(p, "utf8");
  const vaultMatch = raw.match(/vault_path:\s*["']?([^"'\n]+)/i);
  if (!vaultMatch?.[1]) return null;
  const rootMatch = raw.match(/vault_juno_root:\s*["']?([^"'\n]+)/i);
  return {
    vaultPath: vaultMatch[1].trim().replace(/\\\\/g, "\\"),
    vaultJunoRoot: rootMatch?.[1]?.trim() ?? "Juno",
  };
}

export function loadDailyInboxConfig(workbench: string): DailyInboxConfig {
  const p = path.join(workbench, "config", "daily-inbox.json");
  if (!existsSync(p)) {
    return {
      enabled: true,
      vaultJunoRoot: "Juno",
      inboxSubdir: "inbox",
      filenamePattern: "{date}-每日任务.md",
      profileFile: "_profile.md",
      deletePreviousDay: true,
    };
  }
  try {
    return JSON.parse(readFileSync(p, "utf8")) as DailyInboxConfig;
  } catch {
    return { enabled: false };
  }
}

export function renderDailyInboxDate(d = new Date()): string {
  return d.toISOString().slice(0, 10);
}

function renderDateInTimezone(d: Date, timezone: string): string {
  try {
    const dtf = new Intl.DateTimeFormat("en-CA", {
      timeZone: timezone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    });
    return dtf.format(d);
  } catch {
    return renderDailyInboxDate(d);
  }
}

function readAutonomyTimezone(workbench: string): string {
  const p = path.join(workbench, "config", "daily-schedule.json");
  if (!existsSync(p)) return "Asia/Shanghai";
  try {
    const cfg = JSON.parse(readFileSync(p, "utf8")) as { autonomyTimezone?: string };
    return cfg.autonomyTimezone?.trim() || "Asia/Shanghai";
  } catch {
    return "Asia/Shanghai";
  }
}

function resolveOutFile(workbench: string, date: string): string | null {
  const yaml = readCfgYaml(workbench);
  if (!yaml) return null;
  const cfg = loadDailyInboxConfig(workbench);
  const root = cfg.vaultJunoRoot?.trim() || yaml.vaultJunoRoot;
  const subdir = cfg.inboxSubdir?.trim() || "inbox";
  const filename = (cfg.filenamePattern ?? "{date}-每日任务.md").replace("{date}", date);
  const out = path.join(yaml.vaultPath, root, subdir, filename);

  // Hard safety: daily inbox file must stay under <vault>/<junoRoot>/.
  const junoRootAbs = path.resolve(path.join(yaml.vaultPath, root));
  const outAbs = path.resolve(out);
  if (!outAbs.startsWith(junoRootAbs + path.sep) && outAbs !== junoRootAbs) {
    return null;
  }
  return out;
}

function firstSentence(text: string): string {
  const line = text.split(/\r?\n/).map((l) => l.trim()).find(Boolean) ?? "";
  return line.slice(0, 120);
}

function buildBody(workbench: string, date: string): string {
  const ctx = loadFounderContext(workbench);
  const focus = ctx.currentFocus.slice(0, 3);
  const notes = ctx.recentNotes.slice(0, 5).map((n) => n.title);
  const lines = [
    `# ${date} 每日任务`,
    "",
    "> Juno 自动生成：基于 _profile 与近期项目笔记（只读）。",
    "",
    "## 给你的三件事",
    "",
  ];
  if (focus.length) {
    lines.push(
      `1. 推进重心：${focus[0]}`,
      `2. 风险前置：${focus[1] ?? "检查昨日未完成事项并定一个最小交付"}`,
      `3. 对外产出：${focus[2] ?? "把今天进展写进公开/可复盘文档"}`,
    );
  } else {
    lines.push(
      "1. 定义今天的唯一北极星任务（可在 2 小时内交付）",
      "2. 处理一个阻塞项（技术、流程、或协作）",
      "3. 产出一条可复盘记录（Execution Log / 项目笔记）",
    );
  }
  lines.push("", "## 近期上下文（只读）", "");
  if (notes.length) {
    for (const n of notes) lines.push(`- ${n}`);
  } else {
    lines.push("- 暂无近期笔记样本");
  }
  if (ctx.ambitionText) {
    lines.push("", "## 对齐提示", "", `- ${firstSentence(ctx.ambitionText)}`);
  }
  lines.push("", "_Generated by Juno daily-inbox._", "");
  return lines.join("\n");
}

function deletePreviousDayFile(workbench: string, todayFile: string, todayDate: string): string[] {
  const cfg = loadDailyInboxConfig(workbench);
  if (cfg.deletePreviousDay === false) return [];
  const dir = path.dirname(todayFile);
  if (!existsSync(dir)) return [];
  const d = new Date(`${todayDate}T12:00:00`);
  d.setDate(d.getDate() - 1);
  const previousDate = renderDailyInboxDate(d);
  const previousName = `${previousDate}-每日任务.md`;
  const deleted: string[] = [];
  for (const name of readdirSync(dir)) {
    if (name !== previousName) continue;
    const full = path.join(dir, name);
    if (path.resolve(full) === path.resolve(todayFile)) continue;
    try {
      unlinkSync(full);
      deleted.push(full);
    } catch {
      // ignore per-file failure
    }
  }
  return deleted;
}

export function generateDailyInbox(workbench: string, date?: string): DailyInboxResult {
  const cfg = loadDailyInboxConfig(workbench);
  if (cfg.enabled === false) return { status: "disabled", reason: "daily-inbox disabled" };
  const todayDate = date ?? renderDateInTimezone(new Date(), readAutonomyTimezone(workbench));
  const out = resolveOutFile(workbench, todayDate);
  if (!out) return { status: "error", reason: "vault path invalid or outside Juno root" };
  if (existsSync(out)) return { status: "skipped", filePath: out, reason: "already generated today" };

  mkdirSync(path.dirname(out), { recursive: true });
  const content = buildBody(workbench, todayDate);
  writeFileSync(out, content, "utf8");
  const deleted = deletePreviousDayFile(workbench, out, todayDate);
  return { status: "created", filePath: out, deleted };
}
